---
- name: Install various softwares to setup windows 10x 64 DevOps workstation
  hosts: windows
  #become: yes
  #become_user: Administrator
  #become_user: SYSTEM
  #become_method: runas
  vars:
      #repository_url: git@github.com:valet2you/DemoGitTest.git
      #repository_path: /c/ubuntufiles
      #key_file: /root/.ssh/id_rsa.github
      #project_name: viki-devops-test
      playbook_dir: "{{ playbook_dir }}" # Defined by Ansible itself
      files_dir: "{{ playbook_dir }}/files/"
  tasks:

    - name: Install mutiple chocolatey packages
      win_chocolatey:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - git
        - virtualbox
        - vagrant
        - conemu
        - insomnia-rest-api-client
      become: yes
      become_user: SYSTEM
      become_method: runas

    - name: Uninstall multiple packages
      win_chocolatey:
        name:
        - Nosoftware1
        - Nosoftware2
        - Nosoftware3
        state: absent
      become: yes
      become_user: SYSTEM
      become_method: runas
