---
- name: Viki windows test playbook
  hosts: windows
  #become: yes
  #become_user: Administrator
  #become_method: runas
  vars:
      #repository_url: git@github.com:valet2you/DemoGitTest.git
      #repository_path: /c/ubuntufiles
      #key_file: /root/.ssh/id_rsa.github
      #project_name: viki-devops-test
      playbook_dir: "{{ playbook_dir }}" # Defined by Ansible itself
      files_dir: "{{ playbook_dir }}/files/"
  tasks:
    - name: Ping all machines in the inventory file
      win_ping:

